config/routes.rb
Rails.application.routes.draw do
  get 'password_reset/new'
  get 'password_reset/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'users/new'#singup
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only:[:edit]
  resources :password_reset,      only:[:new,:create,:edit,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  before_action :get_user,          only:[:edit,:update]
  before_action :valid_user,        only:[:edit,:update]
  before_action :check_expiration,  only:[:edit,:update]#パスワード再設定の有効期限が切れていないか



  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password.empty?] #新しいパスワードが空文字列になっていないか (ユーザー情報の編集ではOKだった)
      @user.errors.add(:password, :blank)
      render 'edit'
    elsif @user.update_attributes(user_params) #新しいパスワードが正しければ、更新する
      log_in @user
      flash[:syccess] = "Password has been reset."
      redirect_to @user
    else
      render 'edit'#無効なパスワードであれば失敗させる (失敗した理由も表示する)
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user =User.find_by(email: params[:email])
    end
    #正しいユーザーかどうか確認する
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated? (:reset, params[:id]))
        redirect_to root_url
      end
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/views/password_reset/edit.html.erb
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) dp |f|%>
      <%= render 'shard/error_messages'%>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class:'form-control' %>

      <%= f.label :password_confirmation, class: 'Confirmation'%>
      <%= f.password_field :password_confirmation, class: 'form-control'%>

      <%= f.submit "Update password", class:"btn btn-primary"%>
    <% end%>
  </div>
</div>

app/views/password_reset/new.html.erb
<% provide(:title,"Forgot password")%>
<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_reset_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Submit", class:"btn btn-primary"%>
    <% end %>
  </div>
</div>