config/routes.rb
Rails.application.routes.draw do
  get 'password_reset/new'
  get 'password_reset/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'users/new'#singup
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only:[:edit]
  resources :password_reset,      only:[:new,:create,:edit,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Micael Hartl</a>
  </small>
  <nav>
    <ul>
      <li> <%= link_to "About", 'static_pages/about' %></li>
      <li> <%= link_to "Contact", 'static_pages/contact'%></li>
      <li> <a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app",'#', id:"logo"%>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",'static_pages/home' %></li>
        <li><%= link_to "Help",'static_pages/help'%></li>
        <% if logged_in? %>
        <li><%= link_to "Users", user_path %></li>
        <li class="dropdown">
          <a href="" class="dropdown-toggle" date-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user)%></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message|%>
      <%= content_tag(:div, message, ckass:"alert alert-#{message_type}")%>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>